### PR TITLE
fix package `:data` visibility so it's compatible with `cacerts()`

### PR DESCRIPTION
**Pull request by lazcamus**
set package `:data` visibility to public so it can be used in a call to `cacerts()`

I stuck a quick check into `examples/apt` tests to verify that it behaves as expected.

### CODE REVIEW

**Comment by lazcamus** [comment]
The `bullseye.lock.json` diff has a spaces vs tabs change that was unintentional ... the diff looks sane with whitespace ignored

I'm not sure if this is a byproduct of another change and the lock file never got regenerated, or maybe my environment is somehow creeping in?

**Comment by thesayyn** [comment]
Yeah, we should be ignoring the lockfiles from formatter. Feel free to revert those lockfile changes.

**Comment by lazcamus** [comment]
@thesayyn lockfile is reverted ... though it'll have a legit change if you re-gen it b/c I added a package

**Comment by thesayyn** [comment]
that's true, sorry, you can regen it.

**Comment by lazcamus** [comment]
> that's true, sorry, you can regen it.

regenned the lockfile and rebased on `main` so the PR should be current

oddly, the spurious whitespace diff I was seeing before is no longer occurring 🤷

**Review by thesayyn — APPROVED** [review]

**Pull request merged**
