### PR TITLE
Handle uncompressed Package files

### PR DESCRIPTION
**Pull request by JonathanPerry651**
E.g. packages.cloud.google.com/apt’s Packages

### CODE REVIEW

**Comment by JonathanPerry651** [comment]
Should I add the cloud.google.com repo to the smoketest bullseye.yaml? Wasn’t sure that you would want that dependency in your tests.

**Review by thesayyn — APPROVED** [review]
Thank you

**Comment by thesayyn** [comment]
> Should I add the cloud.google.com repo to the smoketest bullseye.yaml? Wasn’t sure that you would want that dependency in your tests.

Yes, please

**Comment by JonathanPerry651** [comment]
> > Should I add the cloud.google.com repo to the smoketest bullseye.yaml? Wasn’t sure that you would want that dependency in your tests.
> 
> Yes, please

Done!

**Review by thesayyn — APPROVED** [review]

**Comment by JonathanPerry651** [comment]
Amazing, thanks for the quick responses - and thanks to you (and any other maintainers, I don't know how to find them out) for your hard work on this repo in general - it's super helpful!

**Pull request merged**
